object_cols: [
  "RAZAO_SOCIAL-CIDADE-UF",
  "BIOCOMBUSTIVEL",
  "ROTA",
  "FIRMA_INSPETORA",
  "ENDERECO_EMISSOR_PRIMARIO",
  "CNPJ",
  "PROCESSO_DE_CERTIFICACAO",
]

int_cols: [
  "CNPJ",
  "PROCESSO_DE_CERTIFICACAO"
]
    
float_cols: [
  "NOTA_DE_EFICIENCIA_ENERGETICO-AMBIENTAL_GCO2EQ/MJ",
  "VOLUME_ELEGIVEL_%",
  "FATOR_PARA_EMISSAO_DE_CBIO_TCO2EQ/L",
]

date_cols: [
  "DATA_DE_APROVACAO_PELA_ANP",
  "VALIDADE"
]

ds_rota: {
  "ETANOL COMBUSTIVEL DE PRIMEIRA GERACAO CANA-DE-ACUCAR":
  "ETANOL 1G CANA",
  "ETANOL COMBUSTIVEL DE PRIMEIRA GERACAO CANA-DE-ACUCAR E MILHO EM USINA INTEGRADA":
  "ETANOL 1G CANA E MILHO",
  "ETANOL COMBUSTIVEL DE PRIMEIRA GERACAO MILHO":
  "ETANOL 1G MILHO",
  "ETANOL COMBUSTIVEL DE PRIMEIRA E SEGUNDA GERACAO PRODUZIDO EM USINA INTEGRADA":
  "ETANOL 1G E 2G",
}

cd_rota: {
  "BIODIESEL": 1,
  "BIOMETANO": 2,
  "ETANOL 1G E 2G": 3,
  "ETANOL 1G CANA": 4,
  "ETANOL 1G CANA E MILHO": 5,
  "ETANOL 1G MILHO": 6,
}

dict_rename_cols: {
    'PROCESSO_DE_CERTIFICACAO': 'PROCESSO_CERTIFICACAO',
    'NOTA_DE_EFICIENCIA_ENERGETICO-AMBIENTAL_GCO2EQ/MJ': 'NOTA_EF_ENERGETICO_AMBIENTAL',
    'VOLUME_ELEGIVEL_%': 'PCT_VOLUME_ELEGIVEL',
    'FATOR_PARA_EMISSAO_DE_CBIO_TCO2EQ/L': 'FATOR_EMISSAO_CBIO',
    'LITROS/CBIO': 'LITROS_CBIO',
    'DATA_DE_APROVACAO_PELA_ANP': 'DT_APROVACAO_ANP',
    'VALIDADE': 'DT_VALIDADE',
    'FIRMA_INSPETORA': 'INSPETORA',
    'ENDERECO_EMISSOR_PRIMARIO': 'ENDERECO_PRIMARIO',
}

ordered_cols: [
    'CNPJ', 'RAZAO_SOCIAL', 'PROCESSO_CERTIFICACAO',
    'CIDADE', 'UF', 'ENDERECO_PRIMARIO',
    'CEP', 'DS_END', 'NO_END',
    'BIOCOMBUSTIVEL', 'ROTA', 'DS_ROTA', 'CD_ROTA',
    'LITROS_CBIO', 'PCT_VOLUME_ELEGIVEL', 'NOTA_EF_ENERGETICO_AMBIENTAL', 
    'FATOR_EMISSAO_CBIO', 'INSPETORA', 'DT_APROVACAO_ANP', 'DT_VALIDADE',
]
